export const FETCH_VEHICLES_REQUEST = "FETCH_VEHICLES_REQUEST";
export const FETCH_VEHICLES_RESPONSE = "FETCH_VEHICLES_RESPONSE";
export const POST_VEHICLE_REQUEST = "POST_VEHICLE_REQUEST";
export const PUT_VEHICLE_REQUEST = "PUT_VEHICLE_REQUEST";
export const DELETE_VEHICLE_REQUEST = "DELETE_VEHICLE_REQUEST";
export const SHOW_MODAL_ADD = "SHOW_MODAL_ADD";
export const SHOW_MODAL_EDIT = "SHOW_MODAL_EDIT";
export const CLOSE_MODAL = "CLOSE_MODAL";



 
 

  